<?php
// Turn a coordinate into a place name, server-side and only server-side.
//
// The station stores where a field recording was made because the model
// needs it - the occurrence filter judges a clip by where it was heard.
// Nothing downstream needs the coordinate itself, so nothing downstream
// gets it: this file is the one place a fix becomes a name, and the API
// sends the name.
//
// Names come from Singapore's 55 planning areas (avian/api/sg-areas.php,
// generated by avian/scripts/build_sg_map.py). A point is named by the
// area that actually contains it - not by the nearest entry in a
// hand-written landmark list, which would be a guess dressed up as a
// fact.
//
// One name is not a planning area. A recording made at the station is
// "Home": the owner already knows where that is, and a visitor who can
// see the site has no business learning the address from it.

declare(strict_types=1);

// How close to the station counts as home. Wide enough to cover a garden
// and a phone's GPS error, narrow enough that the end of the street is
// still the street.
const AVIAN_HOME_RADIUS_M = 300.0;

const AVIAN_PLACE_HOME = 'Home';

/**
 * The generated area table, loaded once.
 *
 * @return array<string, list<list<float>>> name => rings, each ring a flat
 *         [lon, lat, lon, lat, ...] list.
 */
function avian_areas(): array {
    static $areas = null;
    if ($areas === null) {
        $path = __DIR__ . '/sg-areas.php';
        $areas = is_file($path) ? (require $path) : [];
        if (!is_array($areas)) $areas = [];
    }
    return $areas;
}

/**
 * Bounding boxes, so a lookup tests four numbers per area and only walks
 * the rings of the one or two it could plausibly be in.
 *
 * @return array<string, array{0:float,1:float,2:float,3:float}>
 */
function avian_area_boxes(): array {
    static $boxes = null;
    if ($boxes !== null) return $boxes;
    $boxes = [];
    foreach (avian_areas() as $name => $rings) {
        $minLon = $minLat = INF;
        $maxLon = $maxLat = -INF;
        foreach ($rings as $ring) {
            for ($i = 0, $n = count($ring); $i < $n; $i += 2) {
                $lon = $ring[$i];
                $lat = $ring[$i + 1];
                if ($lon < $minLon) $minLon = $lon;
                if ($lon > $maxLon) $maxLon = $lon;
                if ($lat < $minLat) $minLat = $lat;
                if ($lat > $maxLat) $maxLat = $lat;
            }
        }
        $boxes[$name] = [$minLon, $minLat, $maxLon, $maxLat];
    }
    return $boxes;
}

/** Even-odd crossing count across every ring, so a hole excludes correctly. */
function avian_point_in_rings(array $rings, float $lon, float $lat): bool {
    $inside = false;
    foreach ($rings as $ring) {
        $n = count($ring);
        for ($i = 0; $i + 3 < $n; $i += 2) {
            $x1 = $ring[$i];     $y1 = $ring[$i + 1];
            $x2 = $ring[$i + 2]; $y2 = $ring[$i + 3];
            if (($y1 > $lat) !== ($y2 > $lat)) {
                $at = $x1 + ($lat - $y1) * ($x2 - $x1) / ($y2 - $y1);
                if ($lon < $at) $inside = !$inside;
            }
        }
    }
    return $inside;
}

/** Metres between two coordinates. Equirectangular is plenty over a city. */
function avian_metres_between(float $lat1, float $lon1, float $lat2, float $lon2): float {
    $dLat = ($lat2 - $lat1) * 111320.0;
    $dLon = ($lon2 - $lon1) * 111320.0 * cos(deg2rad(($lat1 + $lat2) / 2));
    return sqrt($dLat * $dLat + $dLon * $dLon);
}

/** The planning area containing a point, or null if it is outside them all. */
function avian_area_at(float $lat, float $lon): ?string {
    $areas = avian_areas();
    foreach (avian_area_boxes() as $name => [$minLon, $minLat, $maxLon, $maxLat]) {
        if ($lon < $minLon || $lon > $maxLon || $lat < $minLat || $lat > $maxLat) continue;
        if (avian_point_in_rings($areas[$name], $lon, $lat)) return $name;
    }
    return null;
}

/**
 * Name a fix.
 *
 * Returns ['place' => label shown to people, 'area' => planning area used
 * to shade the map, or null]. The two differ only at the station, where
 * the label is "Home" and the area is still real so the map has somewhere
 * to put the mark.
 *
 * A position outside the areas entirely - somebody recording abroad -
 * gets no name rather than a wrong one. The caller decides what to say
 * about that; this function does not invent geography.
 *
 * @return array{place: ?string, area: ?string}
 */
function avian_place_for(?float $lat, ?float $lon,
                         ?float $homeLat = null, ?float $homeLon = null): array {
    if ($lat === null || $lon === null) return ['place' => null, 'area' => null];

    $area = avian_area_at($lat, $lon);
    if ($homeLat !== null && $homeLon !== null && ($homeLat || $homeLon)
        && avian_metres_between($lat, $lon, $homeLat, $homeLon) <= AVIAN_HOME_RADIUS_M) {
        return ['place' => AVIAN_PLACE_HOME, 'area' => $area];
    }
    return ['place' => $area, 'area' => $area];
}
